from setuptools import setup, find_packages

try:
    setup(name='UTC', version='1.0', python_requires='>=3.9', packages=find_packages())
finally:
    # Initialize data directory in /utc
    from os import mkdir
    data_path: str = "utc/data"
    dirs_to_make: list = [
        # Data
        data_path,
        # Domains
        data_path + "/domains",
        # Maps
        data_path + "/maps",
        data_path + "/maps/osm",
        data_path + "/maps/osm/original",  # Folder containing ".osm" maps downloaded from OpenStreetMap
        data_path + "/maps/osm/filtered",  # Folder containing ".osm" maps filtered by osm_filter (only road network)
        data_path + "/maps/sumo",  # Folder containing ".net.xml" maps created by netedit from "_filtered.osm" maps
        data_path + "/maps/information",  # Folder containing ".info" files recording how graph was created
        # Planners
        data_path + "/planners",  # Folder containing pddl planners (must be added by user)
        # Scenarios
        data_path + "/scenarios",  # Folder containing SUMO scenarios
        data_path + "/scenarios/problems",    # Folder containing pddl problem files
        data_path + "/scenarios/results",     # Folder containing pddl result files (generated by planners)
        data_path + "/scenarios/routes",      # Folder containing ".rou.xml" files of simulation
        # Scenarios/simulation
        data_path + "/scenarios/simulation",  # Folder containing ".sumocfg" files
        data_path + "/scenarios/simulation/generated",  # Folder containing ".sumocfg" files generated by user
        data_path + "/scenarios/simulation/planned",    # Folder containing ".sumocfg" files generated from pddl results
        data_path + "/scenarios/simulation/statistics",  # Folder containing statistics of simulation
        # Folder containing ".info" files recording how scenario was generated
        data_path + "/scenarios/simulation/information",
    ]
    # Create directories
    print("Creating directories")
    for directory in dirs_to_make:
        try:
            mkdir(directory)
        except FileExistsError as e:
            continue
    print("Finished creating directories")
