from setuptools import setup, find_packages

try:
    setup(name='UTC', version='1.0', packages=find_packages())
finally:
    # Initialize data directory in /utc
    from os import mkdir
    data_path: str = "/utc/data"
    dirs_to_make: list = [
        data_path,  # /data
        data_path + "/domains",  # /data/domains
        # Maps
        data_path + "/maps",
        data_path + "/maps/osm",
        data_path + "/maps/osm/original",
        data_path + "/maps/osm/filtered",
        data_path + "/maps/sumo",
        # Planners
        data_path + "/planners",  # Folder containing pddl planners
        # Scenarios
        data_path + "/scenarios",  # Folder containing SUMO scenarios
        data_path + "/scenarios/problems",    # Folder containing pddl problem files
        data_path + "/scenarios/results",     # Folder containing pddl result files (generated by planners)
        data_path + "/scenarios/statistics",  # Folder containing statistics of simulation
        data_path + "/scenarios/routes",      # Folder containing ".rou.xml" files of simulation
        # Scenarios/simulation
        data_path + "/scenarios/simulation",  # Folder containing ".sumocfg" files
        data_path + "/scenarios/simulation/generated",  # Folder containing ".sumocfg" files generated by user
        data_path + "/scenarios/simulation/planned",    # Folder containing ".sumocfg" files generated from pddl results
        # Folder containing ".info" files holding commands used to generate scenario
        data_path + "/scenarios/simulation/information",
    ]
    # Create directories
    for directory in dirs_to_make:
        try:
            mkdir(directory)
        except FileExistsError as e:
            continue
